---
# Copyright (C) 2018 Expedia Inc.
# Licensed under the Apache License, Version 2.0 (the "License");

- name: Install PIP
  yum: name=python-pip state=present

- name: Install lxml
  pip: name=lxml
