- hosts: all
  become: true

  vars:
    server_yaml: "${server_yaml}"
    federation_yaml: "${federation_yaml}"
    heapsize: "{{ (ansible_memtotal_mb * 0.8)|int }}"

  tasks:

  - name: cleanup packages
    yum:
      name:
        - java-1.7.0-openjdk
      state: absent

  - name: install binaries
    yum:
      name:
        - java-1.8.0-openjdk
        - wget
        - unzip
        - jq
        - htop
        - telnet
        - nc
      state: present

  - name: install waggle-dance
    yum:
      name: http://search.maven.org/remotecontent?filepath=com/hotels/waggle-dance-rpm/${waggledance_version}/waggle-dance-rpm-${waggledance_version}.rpm
      state: present

  - name: server yaml
    copy:
      dest: /opt/waggle-dance/conf/waggle-dance-server.yml
      content: "{{ server_yaml|b64decode }}"

  - name: federation yaml
    copy:
      dest: /opt/waggle-dance/conf/waggle-dance-federation.yml
      content: "{{ federation_yaml|b64decode }}"
    notify:
      - restart-waggledance

  - name: server conf
    copy:
      dest: /opt/waggle-dance/service/waggle-dance-core-latest-exec.conf
      content: |
        LOG_FOLDER=/var/log/waggle-dance/
        JAVA_OPTS="-Xmx{{ heapsize }}m -Xms{{ heapsize }}m -XX:+UseG1GC -XX:G1ReservePercent=15 -Dlog4j.configurationFile=/opt/waggle-dance/conf/log4j2.xml -Dlogging.config=/opt/waggle-dance/conf/log4j2.xml"
        RUN_ARGS="--server-config=/opt/waggle-dance/conf/waggle-dance-server.yml --federation-config=/opt/waggle-dance/conf/waggle-dance-federation.yml"
    notify:
      - restart-waggledance

  - name: state waggle-dance
    service:
      name: waggle-dance
      enabled: yes
      state: started

  handlers:

  - name: restart-waggledance
    service:
      name: waggle-dance
      enabled: yes
      state: restarted
